name: quarto-r-binder
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab

  # Quarto CLI to render .qmd
  - quarto
  - deno
  # R + core rendering tooling
  - r-base=4.3
  - r-knitr
  - r-rmarkdown

  # Packages used in your .qmd
  - r-httr
  - r-jsonlite
